### ISSUE TITLE
push issue

### ISSUE THREAD

**Issue by greg-sideyr** [gsheppar/Prisma-SD-WAN-SNMP#1]
Has there been a syntax change for applying new settings? Using this, I have been able to get the existing settings and remove settings, but I am unable to add new settings, getting the error "Error creating SNMP Agent on [NAME]" on each device. Thank you!

**Comment by gsheppar** [comment]
I will check this out this weekend

**Comment by greg-sideyr** [comment]
Thank you! I tried reading through the API documentation to update it, but I'm still new with this and got lost in it.

**Comment by gsheppar** [comment]
I put in a debug to see what the error is for you. More then likely your SNMP schema data is incorrect and its throwing a warning. Run it again and let me know. 

data = {"description":"Example","tags":None,"v2_config":{"community":"test","enabled":"true"},"v3_config":None}

**Comment by greg-sideyr** [comment]
Thank you! Below is the output when I attempt to run the script directly as written. --get and --destroyall work as intended as shown below.

**no modifier output**

> $ python SNMPAgent.py
> WARNING: cloudgenix SDK will soon end support for python versions 2.x, 3.6 and below. Please update your python environment to 3.7 or above by the end of September 2023.
> CloudGenix: Example script: SNMP vv1 (https://api.elcapitan.cloudgenix.com)
> 
> Error creating SNMP Agent on AzureDC_ION01                                                                    
> REQUEST: POST /v2.1/api/tenants/21648146454/sites/16509011308100192/elements/16509014085470147/snmpagents     
> REQUEST HEADERS:                                                                                              
>         User-Agent: python-requests/2.28.2 (CGX SDK v6.2.2b1)                                                 
>         Accept-Encoding: gzip, deflate                                                                        
>         Accept: application/json                                                                              
>         Connection: keep-alive                                                                                
>         X-Auth-Token: <SENSITIVE - NOT SHOWN BY DEFAULT>                                                      
>         Content-Type: application/json                                                                        
>         Cookie: AUTH_TOKEN="<SENSITIVE - NOT SHOWN BY DEFAULT>"                                               
>         Content-Length: 114                                                                                   
> REQUEST BODY:                                                                                                 
> {                                                                                                             
>     "description": "Example",                                                                                 
>     "tags": null,                                                                                             
>     "v2_config": {                                                                                            
>         "community": "test",                                                                                  
>         "enabled": "true"                                                                                     
>     },                                                                                                        
>     "v3_config": null                                                                                         
> }                                                                                                             
>                                                                                                               
> RESPONSE: 400 Bad Request                                                                                     
> RESPONSE HEADERS:                                                                                             
>         Date: Sat, 29 Jul 2023 21:39:59 GMT                                                                   
>         Content-Length: 270                                                                                   
>         Connection: keep-alive                                                                                
>         Server: nginx                                                                                         
> RESPONSE DATA:                                                                                                
> {                                                                                                             
>     "_etag": 0,                                                                                               
>     "_content_length": "0",                                                                                   
>     "_schema": 0,                                                                                             
>     "_created_on_utc": 0,                                                                                     
>     "_updated_on_utc": 0,                                                                                     
>     "_status_code": "400",                                                                                    
>     "_request_id": "1690666799165019899998152308816361248436",                                                
>     "_error": [                                                                                               
>         {                                                                                                     
>             "code": "INVALID_JSON_INPUT",                                                                     
>             "message": "\"Input JSON does not have all required attributes.\""                                
>         }                                                                                                     
>     ]                                                                                                         
> }                                                                                                             
> None                                                                                                          
> 

**--get output**

> $ python SNMPAgent.py --get
> WARNING: cloudgenix SDK will soon end support for python versions 2.x, 3.6 and below. Please update your python environment to 3.7 or above by the end of September 2023.
> CloudGenix: Example script: SNMP vv1 (https://api.elcapitan.cloudgenix.com)
> 
> ION Name: PHL01
> [{'id': '1690667046171005096', '_etag': 1, '_schema': 1, '_created_on_utc': 16906670461710050, '_updated_on_utc': 16906670461710050, '_debug': None, '_info': None, '_warning': None, '_error': None, 'tags': None, 'description': 'test //gmb', 'v2_config': {'enabled': True, 'community': 'testing'}, 'v3_config': None, 'system_contact': None, 'system_location': None}]
> 

**--destroyall output**

> $ python SNMPAgent.py --destroyall
> WARNING: cloudgenix SDK will soon end support for python versions 2.x, 3.6 and below. Please update your python environment to 3.7 or above by the end of September 2023.
> CloudGenix: Example script: SNMP vv1 (https://api.elcapitan.cloudgenix.com)
> 
> Deleted SNMP Agent on PHL01

**Comment by greg-sideyr** [comment]
Have you had any luck narrowing this down? Thank you!

**Comment by gsheppar** [comment]
Try this

data = {"description":"Example","tags":None,"v2_config":{"community":"test","enabled":"true"},"v3_config":None, 'system_contact': None, 'system_location': None}

**Comment by greg-sideyr** [comment]
that did it, thank you!
